### ISSUE TITLE
I am the only Hero

### ISSUE THREAD

**Issue by cinderblock** [enomic/enomic#17]
I recently added myself as a Hero, but to the top of the list. I inadvertently (or not, you decide :stuck_out_tongue_winking_eye:) became the only person to be able to approve new code.

To figure out what's wrong, I want to see server outputs. I'm planning on writing a little code that, on every PR that is approved, starts a new gist and dumps its output there.

See https://github.com/enomic/enomic/pull/16#issuecomment-132075114

**Comment by enomic** [comment]
Here we go.. please don't be an undercover villain, and good luck fixing it! I'll be around for a little while tonight in case you get stuck

**Comment by ZainRizvi** [comment]
I've fixed this bug. Please accept this pull request to fix it: https://github.com/enomic/enomic/pull/23

**Comment by ZainRizvi** [comment]
Good job villianing :+1:

**Comment by enomic** [comment]
Thanks for the logging code, cinderblock! The problem still persists unfortunately

**Comment by enomic** [comment]
Ok I think we are fully back online and everyone can sign code and be heroes
